version: "2"

services:
  orders:
    build: ./orders
    ports:
      - 9002:3002
    restart: always

  products:
    build: ./products
    ports:
      - 9001:3001
    restart: always

  users:
    build: ./users
    # difference between expose and ports?
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users
    ports:
      - "4000:4000"
